### ISSUE TITLE
blocker: Unable to run the app

### ISSUE THREAD

**Issue by shebin-tw** [subbikcha-k/Bulls-Eye#1]
<img width="282" alt="Screenshot 2022-09-08 at 3 41 34 PM" src="https://user-images.githubusercontent.com/65023866/189096706-16c36d04-b2d6-4d51-a8a8-103035aa8dfe.png">

<img width="292" alt="Screenshot 2022-09-08 at 3 41 29 PM" src="https://user-images.githubusercontent.com/65023866/189096715-ef576658-29d5-4530-97d5-f34f9a635e29.png">

Unable to run the app, seems like html file is missing. 

If you are unable to reproduce this issue, try to clone the repo in a new folder in your mac.

**Comment by subbikcha-k** [comment]
@shebin-tw I have fixed this issue regarding html file missing
